FROM openjdk:8-jre-alpine
MAINTAINER Synoa GmbH <we@synoa.de>
ENTRYPOINT ["java", "-jar", "/getting-started.jar"]

ADD target/getting-started.jar /
ADD development.properties /application.properties


